// Package models contains the types for schema 'emind_software_center'.
package models

// GENERATED BY XO. DO NOT EDIT.

import (
	"database/sql"
	"errors"
)

// Insert inserts the ScRelease to the database.
func (sr *ScRelease) AddRelaseAndUpdateProduct(db *sql.DB) error {
	var err error

	// if already exist, bail
	if sr._exists {
		return errors.New("insert failed: already exists")
	}

	// sql insert query, primary key provided by autoincrement
	const sqlstr = `INSERT INTO emind_software_center.sc_release (` +
		`product_ID, product_name, version, icon_url, download_url, changelog, package_size, package_type, release_grade, grade_count, release_date` +
		`) VALUES (` +
		`?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?` +
		`)`

	const sqlstr1 = `SELECT product_name FROM sc_product WHERE ID = ?`

	const sqlstr2 = `UPDATE emind_software_center.sc_product SET ` +
		`release_ID = ?, icon_url = ? ` +
		`WHERE ID = ?`

	tx, err := db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()
	// run query
	if err = tx.QueryRow(sqlstr1, sr.ProductID).Scan(&sr.ProductName); err != nil {
		return err
	}
	XOLog(sqlstr, sr.ProductID, sr.ProductName, sr.Version, sr.IconURL, sr.DownloadURL, sr.Changelog, sr.PackageSize, sr.PackageType, sr.ReleaseGrade, sr.GradeCount, sr.ReleaseDate)
	res, err := tx.Exec(sqlstr, sr.ProductID, sr.ProductName, sr.Version, sr.IconURL, sr.DownloadURL, sr.Changelog, sr.PackageSize, sr.PackageType, sr.ReleaseGrade, sr.GradeCount, sr.ReleaseDate)
	if err != nil {
		return err
	}

	// retrieve id
	id, err := res.LastInsertId()
	if err != nil {
		return err
	}

	// run query
	XOLog(sqlstr2, id, sr.IconURL, sr.ProductID)
	_, err = tx.Exec(sqlstr2, id, sr.IconURL, sr.ProductID)
	if err != nil {
		return err
	}

	if err := tx.Commit(); err != nil {
		return err
	}

	// set primary key and existence
	sr.ID = uint(id)
	sr._exists = true

	return nil
}

// ScReleaseByIDs retrieves rows from 'emind_software_center.sc_release' as a ScRelease.
//
// Generated from index 'sc_release_ID_pkey'.
func ScReleaseByIDs(db *sql.DB, ids []uint) ([]*ScRelease, error) {
	var err error

	// sql query
	const sqlstr = `SELECT ` +
		`product_ID, version, product_name, icon_url, download_url, changelog, package_size, package_type ` +
		`FROM emind_software_center.sc_release ` +
		`WHERE ID = ?`

	stmt, err := db.Prepare(sqlstr)
	if err != nil {
		return nil, err
	}
	defer stmt.Close()

	srs := make([]*ScRelease, 0, 20)
	for _, id := range ids {
		// run query
		XOLog(sqlstr, id)
		sr := &ScRelease{
			_exists: true,
		}

		err = stmt.QueryRow(id).Scan(&sr.ProductID, &sr.Version, &sr.ProductName, &sr.IconURL, &sr.DownloadURL, &sr.Changelog, &sr.PackageSize, &sr.PackageType)
		if err != nil {
			continue
			//return nil, err
		}
		srs = append(srs, sr)
	}

	return srs, nil
}
